GET http://localhost:8000/books

###
GET http://localhost:8000/books/1

###
POST http://localhost:8000/books
Content-Type: application/json

{
    "title": "Buku Tatang Supratman dari rest-client V2",
    "author": "John Doe",
    "price": 80000
}

###
PUT http://localhost:8000/books/2
Content-Type: application/json

{
    "title": "Buku Tatang Supratman V20",
    "author": "Cucu John Doe Junior",
    "price": 180000
}

###
DELETE http://localhost:8000/books/2


# Auth Test
###
GET http://localhost:8000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsIm5hbWUiOiJKYW5lIERvZSIsImVtYWlsIjoiSmFuZUBnbWFpbC5jb20iLCJyb2xlIjoic3VwZXJhZG1pbiIsImlhdCI6MTcxNjk3ODM2NCwiZXhwIjoxNzE2OTc4NDI0fQ.tiwB9pgNKN3Sfus9nfgLjnPd5B7t_-VTxJnI3c_Gi8c

###
GET http://localhost:8000/users/b33d92fc-15d3-4932-805c-904529926d65
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsIm5hbWUiOiJKYW5lIERvZSIsImVtYWlsIjoiSmFuZUBnbWFpbC5jb20iLCJyb2xlIjoic3VwZXJhZG1pbiIsImlhdCI6MTcxNjk3NzkyMCwiZXhwIjoxNzE2OTc3OTgwfQ.9Y1dnEQQ7llohSJ-JevoaSXMdwR35xckQrR26EyYLa8

###
POST http://localhost:8000/users/create
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjgsIm5hbWUiOiJNZW1iZXIgZHVhIiwiZW1haWwiOiJtZW1iZXIyQGdtYWlsLmNvbSIsImlhdCI6MTcxNjk3NTYwNCwiZXhwIjoxNzE2OTc1NjY0fQ.93ZN3KplhWf34E5fsj58cFQFhRrX5GjE_5bdYTWoQeM
Content-Type: application/json

{
    "name": "Member dua",
    "email": "member2@gmail.com",
    "password": "123456",
    "confPassword": "123456",
    "role": "member"
}

###
PUT http://localhost:8000/users/update/ee2987d1-0212-40b6-845d-98279ddc8025
Content-Type: application/json

{
    "name": "Member baru v2",
    "email": "member@gmail.com",
    "password": "",
    "confPassword": "",
    "role": "admin"
}

###
DELETE http://localhost:8000/users/delete/ee2987d1-0212-40b6-845d-98279ddc8025

###
GET http://localhost:8000/token


###
POST http://localhost:8000/register
Content-Type: application/json

{
    "name": "Member baru",
    "email": "member@gmail.com",
    "password": "123456",
    "confPassword": "123456"
}

###
POST http://localhost:8000/login
Content-Type: application/json

{
    "email": "jane@gmail.com",
    "password": "123456"
}

###
DELETE http://localhost:8000/logout

###
GET http://localhost:8000/whoami
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsIm5hbWUiOiJKYW5lIERvZSIsImVtYWlsIjoiSmFuZUBnbWFpbC5jb20iLCJyb2xlIjoic3VwZXJhZG1pbiIsImlhdCI6MTcxNjk3ODA0MCwiZXhwIjoxNzE2OTc4MTAwfQ.2dDaVppUpXfjZK5rMG2rgIdXyl96lQZG20iY00OYAyc